---
- hosts: localhost
  tasks:
    - name: Ensure NTP (for the time synchronization ) is installed
      apt:
        name: NTP
        state: present
    - name: Ensure NTP is running
      service:
        name: ntpd
        state: started
        enabled: yes