# _*_ mode: ruby _*_
# vi: set ft=ruby :

# we are going to manage three VM's, Two for app server and one for DB server

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.ssh.insert_key = true
    config.vm.provider :virtualbox do |vb|
        vb.memory = 256
        vb.cpus = 2
        vb.linked_clone = true
        vb.gui = false
    end
    
    # Application Server1 configuration
    config.vm.define "App1" do|app|
        app.vm.hostname = "orc-app1.dev"
        app.vm.box = "centos/7"
        app.vm.network :private_network, ip: "192.168.60.11"
    end
    
    # Application Server2 configuration
    config.vm.define "App2" do|app|
        app.vm.hostname = "orc-app2.dev"
        app.vm.box = "centos/7"
        app.vm.network :private_network, ip: "192.168.60.12"
    end
    # Application Server2 configuration
    config.vm.define "DB" do|app|
        app.vm.hostname = "orc-db.dev"
        app.vm.box = "centos/7"
        app.vm.network :private_network, ip: "192.168.60.13"
    end
end
